blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog', BlogListView.as_view(), name='blog'),
    path('blog/create', BlogCreateView.as_view(), name='blog_create'),
    path('blog/detail/<int:pk>', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/<int:pk>/update', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete', BlogDeleteView.as_view(), name='blog_delete'),

]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import HomeView, ContactsView, ProductDetailView, ProductList

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('', ContactsView.as_view(), name='contacts'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='product_ditail'),
    path('home', ProductList.as_view(), name='product_list')
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок', help_text='Введите заголовок')
    content = models.TextField(verbose_name='Содержимое', help_text='Введите описание', blank=True)
    preview = models.ImageField(upload_to='media/images', verbose_name='Фотография', help_text='Загрузите изображение', blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания',help_text='Введите дату создания', blank=True)
    published = models.BooleanField(verbose_name="Признак публикации", help_text="Укажите признак публикации", default=True,)
    number_views = models.PositiveIntegerField(verbose_name="Количество просмотров", help_text="Укажите количество просмотров", default=0,)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

catalog/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название продукта', help_text='Введите название продукта')
    description = models.TextField(verbose_name='Описание продукта', help_text='Введите описание продукта', blank=True)
    image = models.ImageField(upload_to='media/images', verbose_name='Фотография', help_text='Загрузите изображение продукта', blank=True)
    category = models.CharField(max_length=150, verbose_name='Название категории продукта', help_text='Введите название категории', blank=True)
    cost = models.IntegerField(verbose_name='цена за покупку', help_text='Введите цену', blank=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания', help_text='Введите дату создания', blank=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения', help_text='Введите дату последнего обновления', blank=True, null=True)

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['name', 'description', 'category', 'cost']


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название категории', help_text='Введите название категории')
    description = models.TextField(verbose_name='Описание категории', help_text='Введите описание категории', blank=True, null=True)

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name', 'description']

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView

from blog.models import Blog


# ListView
class BlogListView(ListView):
    model = Blog
    template_name = "blog/blog.html"

    def get_queryset(self):
        return Blog.objects.filter(published=True)


# DetailView
class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.number_views += 1
        self.object.save()
        return self.object


# CreateView
class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'content', 'preview', 'published', 'number_views',)
    success_url = reverse_lazy('blog:blog')


# UpdateView
class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview', 'published', 'number_views',)
    success_url = reverse_lazy('blog:blog')

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])

# DeleteView
class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog')

catalog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView

from catalog.models import Product

class HomeView(TemplateView):
    template_name = "catalog/home.html"

# def home(request):
#     return render(request, 'home.html')

class ContactsView(TemplateView):
    template_name = 'catalog/contacts.html'

# def contacts(request):
#     return render(request, 'contacts.html')


class ProductDetailView(DetailView):
    model = Product

# def product_ditail(request, pk):
#     product = Product.objects.get(pk=pk)
#     context = {
#         "product_name": product.name,
#         "product_description": product.description,
#         "product_image": product.image,
#         "product_category": product.category,
#         "product_cost": product.cost,
#         "product_created_at": product.created_at,
#         "product_updated_at": product.updated_at,
#                }
#     return render(request, 'product_detail.html', context)

# catalog/product_list.html detail


class ProductList(ListView):
    model = Product


# def product_list(request):
#     products = Product.objects.all()
#     context = {
#         "products": products,
#     }
#     return render(request, 'home.html', context=context)

blog/templates/blog/base.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> <!--Кодировка -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title> <!-- Заголовок -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>
<body>
<a class="btn btn-primary" href="{% url 'blog:blog_create' %}" role="button">Создать блог</a>

{% include 'blog/header.html' %}
{% block content %}{% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Блог
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>

<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
</body>
</html>

blog/templates/blog/blog.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="container">
    <div class="row text-center">
        {% for blog in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">

                <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ blog.title }}</h4>
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{ blog.content }}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>{{ blog.preview }}</li>
                                <li>{{ blog.created_at }}</li>
                                <li>{{ blog.published }}</li>
                                <li>{{ blog.number_views }}</li>
                            </ul>
                            <a class="btn btn-primary" href="{% url 'blog:blog_detail' blog.pk %}" role="button">Посмотреть</a>
                            <a class="btn btn-primary" href="{% url 'blog:blog_update' blog.pk %}" role="button">Редактировать</a>
                            <a class="btn btn-primary" href="{% url 'blog:blog_delete' blog.pk %}" role="button">Удалить</a>
                        </div>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base.html' %}
{% block title %}Создать блог{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <p class="card-text">Действительно хотите удалить блог?{{ object.title}}</p>
                    <div class="card-body">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">
                            Сохранить
                        </button>
                        <a class="btn btn-primary" href="{% url 'blog:blog' %}" role="button">Отмена</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% block title %}Страница блога{% endblock %}
{% block content %}
<body>
    <h1>Информация о блоге</h1>
    <p>Заголовок: {{ object.title }}</p>
    <p>Содержимое: {{ object.content }}</p>
    <p>Превью: <img src="/media/{{ object.preview }}" alt="{{ object.preview }}"></p>
    <p>Дата создания: {{ object.created_at }}</p>
    <p>Признак публикации: {{ object.published }}</p>
    <p>Количество просмотров: {{ object.number_views }}</p>
    <a class="btn btn-primary" href="{% url 'blog:blog' %}" role="button">Назад</a>

</body>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}
{% block title %}Создать блог{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form class="row" method="post" enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row text-center">
        {% for product in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">

                <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{ product.cost }}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>{{ product.description|truncatechars:100 }}</li>
                                <li>{{ product.category }}</li>
                                <li>{{ product.created_at }}</li>
                                <li>{{ product.updated_at }}</li>
                            </ul>
                            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                        </div>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/header.html
<header>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Blog</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
    </div>

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Blog</h1>
        <p class="lead">Удобный сервис просмотра блогов</p>
</div>
</header>

catalog/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> <!--Кодировка -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skypro Homework</title> <!-- Заголовок -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>
<body>

{% include 'header.html' %}
{% block content %}{% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>

<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
</body>
</html>

catalog/templates/catalog/base.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8"> <!--Кодировка -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skypro Homework</title> <!-- Заголовок -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>
<body>

{% include 'catalog/header.html' %}
{% block content %}{% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>

<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block title %}Контакты{% endblock %}
{% block content %}
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}

catalog/templates/catalog/header.html
<header>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
    </div>

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">Skystore</h1>
        <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
            продать</p>
</div>
</header>

catalog/templates/catalog/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>

<div class="container">
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Удобный сервис рассылок</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">$ 140</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- Неограниченная лицензия</li>
                        <li>- Поддержка</li>
                        <li>- Установка на сервер</li>
                        <li>- Получение обновлений</li>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
<!--                    <li><a class="text-muted" href="https://sky.pro/#giftpopup">Мы пишем</a></li>-->
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% block title %}Страница продукта{% endblock %}
{% block content %}
<body>
    <h1>Информация о продукте</h1>
    <p>Имя: {{ object.name }}</p>
    <p>Описание: {{ object.description }}</p>
    <p>Фото: <img src="/media/{{ object.image }}" alt="{{ object.image }}"></p>
    <p>Категория: {{ object.category }}</p>
    <p>Цена: {{ object.cost }}</p>
    <p>Дата созданя: {{ object.created_at }}</p>
    <p>Дата последнего изменения: {{ object.updated_at }}</p>

</body>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="container">
    <div class="row text-center">
        {% for product in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">

                <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{ product.cost }}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>{{ product.description|truncatechars:100 }}</li>
                                <li>{{ product.category }}</li>
                                <li>{{ product.created_at }}</li>
                                <li>{{ product.updated_at }}</li>
                            </ul>
                            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                        </div>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

catalog/templates/contacts.html
{% extends 'base.html' %}

{% block title %}Контакты{% endblock %}
{% block content %}
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}

catalog/templates/home.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row text-center">
        {% for product in products %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">

                <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">{{ product.cost }}</h1>
                            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                                <li>{{ product.description|truncatechars:100 }}</li>
                                <li>{{ product.category }}</li>
                                <li>{{ product.created_at }}</li>
                                <li>{{ product.updated_at }}</li>
                            </ul>
                            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                        </div>

            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}